export { VmTabContent } from './VmTabContent'
export { DatabaseTabContent } from './DatabaseTabContent'
export { IamTabContent } from './IamTabContent'
export { NetworkTabContent } from './NetworkTabContent'
export { StorageTabContent } from './StorageTabContent'
