name: Cleanup GHCR

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    uses: freecloudinitiative/.github/.github/workflows/cleanup-ghcr.yml@2816605944e9c3355e401d527f7f725b05b71ce5
    secrets: inherit
