name: pr-checker
on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: pr-checker-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: freecloudinitiative/.github/.github/workflows/frontend-pr-checker.yml@main
    secrets: inherit
